name       : firefox
version    : 74.0.1
release    : 188
source     :
    - https://ftp.mozilla.org/pub/firefox/releases/74.0.1/source/firefox-74.0.1.source.tar.xz : 62e4297b682fad1ea50d8e32fc51c811169f8edec8d12d2aab0ea60b3197f011
    - https://getsol.us/sources/mozilla/firefox-74.0.1-langpacks.tar.xz : b280f787783dbbfa0fbec54d2b3a582dddfd28977c90bb258a742fabadf34192
license    :
    - GPL-2.0-or-later
    - MPL-2.0
component  : network.web.browser
summary    : Firefox web browser
description: |
    Mozilla Firefox is an open-source web browser, designed for standards compliance, performance and portability. Its functionality can be enhanced via a plethora of extensions.
clang      : yes
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(atk)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libevent)
    - pkgconfig(libpulse)
    - pkgconfig(libturbojpeg)
    - pkgconfig(pango)
    - pkgconfig(pixman-1)
    - pkgconfig(sqlite3)
    - pkgconfig(x11)
    - pkgconfig(xcomposite)
    - pkgconfig(xt)
    - autoconf213
    - bzip2-devel
    - cargo
    - cbindgen
    - llvm-clang
    - nodejs-devel
    - noto-sans-ttf
    - xorg-server-xvfb
    - yasm
rundeps    :
    - ffmpeg
environment: |
    export MOZ_NOSPAM=1
    export MOZBUILD_STATE_PATH=$PWD
setup      : |
    cp $pkgfiles/mozilla-api-key .
    cp $pkgfiles/config .mozconfig
    sed 's@\#\#JOBCOUNT\#\#@%JOBS%@' -i .mozconfig
    echo "ac_add_options --with-mozilla-api-keyfile=${workdir}/mozilla-api-key" >> .mozconfig
    pushd third_party/python/psutil/
    patch -p1 < $pkgfiles/Future-proof-disk_io_counters.patch
    popd
build      : |
    # Instrument build
    echo "ac_add_options --enable-profile-generate=cross" >> .mozconfig
    ./mach build

    # Package and run automated benchmarks for profiling
    ./mach package
    LLVM_PROFDATA=llvm-profdata JARLOG_FILE="$PWD/jarlog" xvfb-run -s "-screen 0 1920x1080x24 -ac +extension GLX +render -noreset" \
    ./mach python build/pgo/profileserver.py

    # Clean for rebuild
    ./mach clobber

    # Profile use build and enable lto
    sed -i '/--enable-profile-generate=cross/d' .mozconfig
    echo "ac_add_options --enable-lto=cross" >> .mozconfig
    echo "ac_add_options --enable-profile-use=cross" >> .mozconfig
    echo "ac_add_options --with-pgo-profile-path=${PWD@Q}/merged.profdata" >> .mozconfig
    echo "ac_add_options --with-pgo-jarlog=${PWD@Q}/jarlog" >> .mozconfig
    ./mach build

    ./mach buildsymbols
install    : |
    # Install locales first
    langpackdir="$installdir/%libdir%/firefox/browser/extensions"
    install -D -d -m 00755 "${langpackdir}"

    tar xf "${sources}/firefox-${version}-langpacks.tar.xz"
    for i in ff_lang_pack/*.xpi; do
        lname="$(basename ${i})"
        install -D -m 00644 "ff_lang_pack/${lname}" "${langpackdir}"/$lname
    done

    DESTDIR=$installdir ./mach install

    mkdir -p $installdir/usr/share/pixmaps
    ln -sv %libdir%/firefox/browser/chrome/icons/default/default128.png $installdir/usr/share/pixmaps/firefox.png

    ln -sv %libdir%/mozilla/plugins $installdir/%libdir%/firefox/plugins

    install -D -m 00644 $pkgfiles/firefox.desktop $installdir/usr/share/applications/firefox.desktop

    # set up defaults
    mkdir -p $installdir/%libdir%/firefox/browser/defaults/preferences
    install -m 00644 $pkgfiles/prefs.js $installdir/%libdir%/firefox/browser/defaults/preferences/prefs.js
    install -m 00644 $pkgfiles/firefox-l10n.js $installdir/%libdir%/firefox/browser/defaults/preferences/firefox-l10n.js
