name       : firefox
version    : 89.0.1
release    : 222
source     :
    - https://ftp.mozilla.org/pub/firefox/releases/89.0.1/source/firefox-89.0.1.source.tar.xz : 3110f0b70fad1af3a306f752d561c4074238c1816698919fe8530c258290401c
    - https://getsol.us/sources/mozilla/firefox-89.0.1-langpacks.tar.xz : c4896ff1b21cf93d5617975cdf09d40b473a72a5e0db6ee7fa77b10146a1ed48
license    :
    - GPL-2.0-or-later
    - MPL-2.0
component  : network.web.browser
summary    : Firefox web browser
description: |
    Mozilla Firefox is an open-source web browser, designed for standards compliance, performance and portability. Its functionality can be enhanced via a plethora of extensions.
clang      : yes
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gbm)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libevent)
    - pkgconfig(libpulse)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libva)
    - pkgconfig(libpci)
    - pkgconfig(x11)
    - pkgconfig(xcomposite)
    - pkgconfig(xt)
    - autoconf213
    - bzip2-devel
    - cargo
    - cbindgen
    - dump_syms
    - llvm-clang
    - nodejs-devel
    - noto-sans-ttf
    - xorg-server-xvfb
    - yasm
rundeps    :
    - ffmpeg
environment: |
    export MOZ_NOSPAM=1
    export MACH_USE_SYSTEM_PYTHON=1
    export MOZBUILD_STATE_PATH=$PWD
    export LDFLAGS="${LDFLAGS/--copy-dt-needed-entries/}" # not supported by lld
    export CFLAGS="${CFLAGS} -fexperimental-new-pass-manager"
    export CXXFLAGS="${CXXFLAGS} -fexperimental-new-pass-manager"
setup      : |
    cp $pkgfiles/{google-safebrowsing,mozilla}-api-key .
    cp $pkgfiles/config .mozconfig
    sed 's@\#\#JOBCOUNT\#\#@%JOBS%@' -i .mozconfig
    echo "ac_add_options --with-mozilla-api-keyfile=${workdir}/mozilla-api-key" >> .mozconfig
    echo "ac_add_options --with-google-safebrowsing-api-keyfile=${workdir}/google-safebrowsing-api-key" >> .mozconfig
    ./mach configure
build      : |
    # Instrument build
    echo "ac_add_options --enable-profile-generate=cross" >> .mozconfig
    ./mach build

    # Package and run automated benchmarks for profiling
    ./mach package
    LLVM_PROFDATA=llvm-profdata JARLOG_FILE="$PWD/jarlog" xvfb-run -s "-screen 0 1920x1080x24 -ac +extension GLX +render -noreset" \
    ./mach python build/pgo/profileserver.py

    # Clean for rebuild
    ./mach clobber

    # Profile use build and enable lto
    sed -i '/--enable-profile-generate=cross/d' .mozconfig
    echo "ac_add_options --enable-lto=cross" >> .mozconfig
    echo "ac_add_options --enable-profile-use=cross" >> .mozconfig
    echo "ac_add_options --with-pgo-profile-path=${PWD@Q}/merged.profdata" >> .mozconfig
    echo "ac_add_options --with-pgo-jarlog=${PWD@Q}/jarlog" >> .mozconfig
    ./mach build
    ./mach buildsymbols
install    : |
    # Install locales first
    langpackdir="$installdir/%libdir%/firefox/browser/extensions"
    install -D -d -m 00755 "${langpackdir}"

    tar xf "${sources}/firefox-${version}-langpacks.tar.xz"
    for i in ff_lang_pack/*.xpi; do
        lname="$(basename ${i})"
        install -D -m 00644 "ff_lang_pack/${lname}" "${langpackdir}"/$lname
    done

    DESTDIR=$installdir ./mach install

    mkdir -p $installdir/usr/share/pixmaps
    ln -sv %libdir%/firefox/browser/chrome/icons/default/default128.png $installdir/usr/share/pixmaps/firefox.png

    ln -sv %libdir%/mozilla/plugins $installdir/%libdir%/firefox/plugins

    install -D -m 00644 $pkgfiles/firefox.desktop $installdir/usr/share/applications/firefox.desktop

    # set up defaults
    mkdir -p $installdir/%libdir%/firefox/browser/defaults/preferences
    install -m 00644 $pkgfiles/prefs.js $installdir/%libdir%/firefox/browser/defaults/preferences/prefs.js
    install -m 00644 $pkgfiles/firefox-l10n.js $installdir/%libdir%/firefox/browser/defaults/preferences/firefox-l10n.js
