name       : firefox
version    : 54.0
release    : 96
source     :
    - https://ftp.mozilla.org/pub/firefox/releases/54.0/source/firefox-54.0.source.tar.xz : 08a9ff6870d904a2af1d03c17c6c44f67413608efb66bb280894d7b92c336a77
    - https://solus-project.com/sources/mozilla/firefox-54.0-langpacks.tar.xz : e401482cd9c241feb1043c2a00c7ff6036f1f6b5035c5e5cd5a2a19fd281e34d
license    :
    - GPL-2.0+
    - MPL-2.0
summary    : Firefox web browser
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(atk)
    - pkgconfig(cairo)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(hunspell)
    - pkgconfig(libevent)
    - pkgconfig(libffi)
    - pkgconfig(libpulse)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(nspr)
    - pkgconfig(nss)
    - pkgconfig(pixman-1)
    - pkgconfig(sqlite3)
    - pkgconfig(vpx)
    - pkgconfig(x11)
    - pkgconfig(xcomposite)
    - pkgconfig(xt)
    - autoconf213
    - cargo
    - libjpeg-turbo-devel
    - rust
    - yasm
rundeps    :
    - ffmpeg
component  : network.web.browser
description: |
    Mozilla Firefox is an open-source web browser, designed for standards compliance, performance and portability. Its functionality can be enhanced via a plethora of extensions.
setup      : |
    # Fix installation directory woes
    %patch -p1 < $pkgfiles/firefox-install-dir.patch

    install $pkgfiles/config mozconfig
    sed 's@\#\#JOBCOUNT\#\#@%JOBS%@' -i mozconfig
build      : |
    # GCC6 produces completely broken Firefox
    export CFLAGS="$CFLAGS -fno-delete-null-pointer-checks -fno-lifetime-dse -fno-schedule-insns2"
    export CXXFLAGS="$CXXFLAGS -fno-delete-null-pointer-checks -fno-lifetime-dse -fno-schedule-insns2"
    %make -f client.mk
install    : |
    # Install locales first
    langpackdir="$installdir/%libdir%/firefox/browser/extensions"
    install -D -d -m 00755 "${langpackdir}"
    
    tar xf "${sources}/firefox-${version}-langpacks.tar.xz"
    for i in lang_pack/*.xpi; do
        lname="$(basename ${i})"
        install -D -m 00644 "lang_pack/${lname}" "${langpackdir}"/$lname
    done
    
    export CFLAGS="$CFLAGS -fno-delete-null-pointer-checks -fno-lifetime-dse -fno-schedule-insns2"
    export CXXFLAGS="$CXXFLAGS -fno-delete-null-pointer-checks -fno-lifetime-dse -fno-schedule-insns2"
    %make_install -f client.mk install INSTALL_SDK= 
    
    mkdir -p $installdir/usr/share/pixmaps
    ln -sv %libdir%/firefox/browser/icons/mozicon128.png $installdir/usr/share/pixmaps/firefox.png
    
    ln -sv %libdir%/mozilla/plugins $installdir/%libdir%/firefox/plugins
      
    install -D -m 00644 $pkgfiles/firefox.desktop $installdir/usr/share/applications/firefox.desktop
    
    # set up defaults
    mkdir -p $installdir/%libdir%/firefox/browser/defaults/preferences
    install -m 00644 $pkgfiles/prefs.js $installdir/%libdir%/firefox/browser/defaults/preferences/prefs.js
    install -m 00644 $pkgfiles/firefox-l10n.js $installdir/%libdir%/firefox/browser/defaults/preferences/firefox-l10n.js

