name       : firefox
version    : '57.0'
release    : 110
source     :
    - https://ftp.mozilla.org/pub/firefox/releases/57.0/source/firefox-57.0.source.tar.xz : 603af00155be87f2c9c58047dd0072971f1cdab1f632695aae6ad072efefbb8f
    - https://solus-project.com/sources/mozilla/firefox-57.0-langpacks.tar.xz : c23552f2e3ed11ef4173c29d2100b77f842f5f4680e9ca3b1b32e9bb6632bb63
license    :
    - GPL-2.0
    - MPL-2.0
component  : network.web.browser
summary    : Firefox web browser
description: |
    Mozilla Firefox is an open-source web browser, designed for standards compliance, performance and portability. Its functionality can be enhanced via a plethora of extensions.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(atk)
    - pkgconfig(cairo)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(hunspell)
    - pkgconfig(libevent)
    - pkgconfig(libffi)
    - pkgconfig(libpulse)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(pixman-1)
    - pkgconfig(sqlite3)
    - pkgconfig(vpx)
    - pkgconfig(x11)
    - pkgconfig(xcomposite)
    - pkgconfig(xt)
    - autoconf213
    - bzip2-devel
    - cargo
    - libjpeg-turbo-devel
    - llvm-clang
    - rust
    - yasm
rundeps    :
    - ffmpeg
setup      : |
    # Fix installation directory woes
    %patch -p1 < $pkgfiles/firefox-install-dir.patch

    # Add NSS SQL Compat patch (thanks Fedora)
    %patch -p1 < $pkgfiles/sqlcompat-ff57-1-backport-730495.patch

    install $pkgfiles/config mozconfig
    sed 's@\#\#JOBCOUNT\#\#@%JOBS%@' -i mozconfig
build      : |
    # GCC6 produces completely broken Firefox
    export CFLAGS="$CFLAGS -fno-delete-null-pointer-checks -fno-lifetime-dse -fno-schedule-insns2"
    export CXXFLAGS="$CXXFLAGS -fno-delete-null-pointer-checks -fno-lifetime-dse -fno-schedule-insns2"
    %make -f client.mk profiledbuild
install    : |
    # Install locales first
    langpackdir="$installdir/%libdir%/firefox/browser/extensions"
    install -D -d -m 00755 "${langpackdir}"
    
    tar xf "${sources}/firefox-${version}-langpacks.tar.xz"
    for i in lang_pack/*.xpi; do
        lname="$(basename ${i})"
        install -D -m 00644 "lang_pack/${lname}" "${langpackdir}"/$lname
    done
    
    export CFLAGS="$CFLAGS -fno-delete-null-pointer-checks -fno-lifetime-dse -fno-schedule-insns2"
    export CXXFLAGS="$CXXFLAGS -fno-delete-null-pointer-checks -fno-lifetime-dse -fno-schedule-insns2"
    %make_install -f client.mk install INSTALL_SDK= 
    
    mkdir -p $installdir/usr/share/pixmaps
    ln -sv %libdir%/firefox/browser/icons/mozicon128.png $installdir/usr/share/pixmaps/firefox.png
    
    ln -sv %libdir%/mozilla/plugins $installdir/%libdir%/firefox/plugins
      
    install -D -m 00644 $pkgfiles/firefox.desktop $installdir/usr/share/applications/firefox.desktop
    
    # set up defaults
    mkdir -p $installdir/%libdir%/firefox/browser/defaults/preferences
    install -m 00644 $pkgfiles/prefs.js $installdir/%libdir%/firefox/browser/defaults/preferences/prefs.js
    install -m 00644 $pkgfiles/firefox-l10n.js $installdir/%libdir%/firefox/browser/defaults/preferences/firefox-l10n.js
