name       : firefox
version    : 55.0.3
release    : 103
source     :
    - https://ftp.mozilla.org/pub/firefox/releases/55.0.3/source/firefox-55.0.3.source.tar.xz : 891836df85f8798c49f7b25661820f64d1311d59703c716eda471819b93ccda2
    - https://solus-project.com/sources/mozilla/firefox-55.0.3-langpacks.tar.xz : 74739a9477532a4208d321b9dbcdc8336c0045d3a29aacf37389ef6a7f7e9d49
license    :
    - GPL-2.0
    - MPL-2.0
component  : network.web.browser
summary    : Firefox web browser
description: |
    Mozilla Firefox is an open-source web browser, designed for standards compliance, performance and portability. Its functionality can be enhanced via a plethora of extensions.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(atk)
    - pkgconfig(cairo)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(hunspell)
    - pkgconfig(libevent)
    - pkgconfig(libffi)
    - pkgconfig(libpulse)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(nspr)
    - pkgconfig(nss)
    - pkgconfig(pixman-1)
    - pkgconfig(sqlite3)
    - pkgconfig(vpx)
    - pkgconfig(x11)
    - pkgconfig(xcomposite)
    - pkgconfig(xt)
    - autoconf213
    - cargo
    - libjpeg-turbo-devel
    - rust
    - yasm
rundeps    :
    - ffmpeg
setup      : |
    # Fix installation directory woes
    %patch -p1 < $pkgfiles/firefox-install-dir.patch

    install $pkgfiles/config mozconfig
    sed 's@\#\#JOBCOUNT\#\#@%JOBS%@' -i mozconfig
build      : |
    # GCC6 produces completely broken Firefox
    export CFLAGS="$CFLAGS -fno-delete-null-pointer-checks -fno-lifetime-dse -fno-schedule-insns2"
    export CXXFLAGS="$CXXFLAGS -fno-delete-null-pointer-checks -fno-lifetime-dse -fno-schedule-insns2"
    %make -f client.mk
install    : "# Install locales first\nlangpackdir=\"$installdir/%libdir%/firefox/browser/extensions\"\
    \ninstall -D -d -m 00755 \"${langpackdir}\"\n\ntar xf \"${sources}/firefox-${version}-langpacks.tar.xz\"\
    \nfor i in lang_pack/*.xpi; do\n    lname=\"$(basename ${i})\"\n    install -D\
    \ -m 00644 \"lang_pack/${lname}\" \"${langpackdir}\"/$lname\ndone\n\nexport CFLAGS=\"\
    $CFLAGS -fno-delete-null-pointer-checks -fno-lifetime-dse -fno-schedule-insns2\"\
    \nexport CXXFLAGS=\"$CXXFLAGS -fno-delete-null-pointer-checks -fno-lifetime-dse\
    \ -fno-schedule-insns2\"\n%make_install -f client.mk install INSTALL_SDK= \n\n\
    mkdir -p $installdir/usr/share/pixmaps\nln -sv %libdir%/firefox/browser/icons/mozicon128.png\
    \ $installdir/usr/share/pixmaps/firefox.png\n\nln -sv %libdir%/mozilla/plugins\
    \ $installdir/%libdir%/firefox/plugins\n  \ninstall -D -m 00644 $pkgfiles/firefox.desktop\
    \ $installdir/usr/share/applications/firefox.desktop\n\n# set up defaults\nmkdir\
    \ -p $installdir/%libdir%/firefox/browser/defaults/preferences\ninstall -m 00644\
    \ $pkgfiles/prefs.js $installdir/%libdir%/firefox/browser/defaults/preferences/prefs.js\n\
    install -m 00644 $pkgfiles/firefox-l10n.js $installdir/%libdir%/firefox/browser/defaults/preferences/firefox-l10n.js\n"
