name       : firefox
version    : '114.0'
release    : 277
source     :
    - https://ftp.mozilla.org/pub/firefox/releases/114.0/source/firefox-114.0.source.tar.xz : d23a0502742f52110ce496837ba82b47bf38d40585633787508ae5be9a5b4bc6
    - https://sources.getsol.us/mozilla/firefox/firefox-114.0-langpacks.tar.xz : b0a8bf001b03cf329d1ddd9577ab46d9a3d2e812c3923379c342d89729fa2786
license    :
    - GPL-2.0-or-later
    - MPL-2.0
component  : network.web.browser
summary    : Firefox web browser
description: |
    Mozilla Firefox is an open-source web browser, designed for standards compliance, performance and portability. Its functionality can be enhanced via a plethora of extensions.
clang      : yes
optimize   : icf-safe
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(bzip2)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gbm)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libevent)
    - pkgconfig(libpulse)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libva)
    - pkgconfig(libpci)
    - pkgconfig(xcomposite)
    - pkgconfig(xt)
    - autoconf213
    - cargo
    - cbindgen
    - dump_syms
    - llvm-clang
    - nodejs-devel
    - noto-sans-ttf
    - xorg-server-xvfb
    - yasm
rundeps    :
    - ffmpeg
environment: |
    export MOZ_NOSPAM=1
    export MACH_BUILD_PYTHON_NATIVE_PACKAGE_SOURCE=system
    export MOZBUILD_STATE_PATH=$PWD
setup      : |
    %patch -p1 < $pkgfiles/firefox-enable-vaapi.patch

    cp $pkgfiles/{google-safebrowsing,mozilla}-api-key .
    cp $pkgfiles/config .mozconfig
    sed 's@\#\#JOBCOUNT\#\#@%JOBS%@' -i .mozconfig
    echo "ac_add_options --with-mozilla-api-keyfile=${workdir}/mozilla-api-key" >> .mozconfig
    echo "ac_add_options --with-google-safebrowsing-api-keyfile=${workdir}/google-safebrowsing-api-key" >> .mozconfig
    ./mach configure
build      : |
    # Instrument build
    echo "ac_add_options --enable-profile-generate=cross" >> .mozconfig
    ./mach build

    # Package and run automated benchmarks for profiling
    ./mach package
    LLVM_PROFDATA=llvm-profdata JARLOG_FILE="$PWD/jarlog" xvfb-run -s "-screen 0 1920x1080x24 -ac +extension GLX +render -noreset" \
    ./mach python build/pgo/profileserver.py

    # Clean for rebuild
    ./mach clobber

    # Profile use build and enable lto
    sed -i '/--enable-profile-generate=cross/d' .mozconfig
    echo "ac_add_options --enable-profile-use" >> .mozconfig
    echo "ac_add_options --with-pgo-profile-path=${PWD@Q}/merged.profdata" >> .mozconfig
    echo "ac_add_options --with-pgo-jarlog=${PWD@Q}/jarlog" >> .mozconfig
    ./mach build
    ./mach buildsymbols
install    : |
    # Install locales first
    langpackdir="$installdir/%libdir%/firefox/browser/extensions"
    install -D -d -m 00755 "${langpackdir}"

    tar xf "${sources}/firefox-${version}-langpacks.tar.xz"
    for i in ff_lang_pack/*.xpi; do
        lname="$(basename ${i})"
        install -Dm00644 "ff_lang_pack/${lname}" "${langpackdir}"/$lname
    done

    DESTDIR=$installdir ./mach install

    mkdir -p $installdir/usr/share/pixmaps
    ln -sv %libdir%/firefox/browser/chrome/icons/default/default128.png $installdir/usr/share/pixmaps/firefox.png

    install -Dm00644 $pkgfiles/firefox.desktop $installdir/usr/share/applications/firefox.desktop

    install -Dm00644 $pkgfiles/firefox.appdata.xml.in $installdir/usr/share/metainfo/firefox.appdata.xml

    # Use a wrapper script to launch in Wayland (temporarily disabled since this breaks default browser detection)
    # rm -v $installdir/usr/bin/firefox
    # install -D -m 00755 $pkgfiles/firefox-wrapper.sh $installdir/usr/bin/firefox

    # set up defaults
    mkdir -p $installdir/%libdir%/firefox/browser/defaults/preferences
    install -m00644 $pkgfiles/prefs.js $installdir/%libdir%/firefox/browser/defaults/preferences/prefs.js
    install -m00644 $pkgfiles/firefox-l10n.js $installdir/%libdir%/firefox/browser/defaults/preferences/firefox-l10n.js
