name       : firefox
version    : 62.0
release    : 137
source     :
    - https://ftp.mozilla.org/pub/firefox/releases/62.0/source/firefox-62.0.source.tar.xz : b3f850581f7d89655a05d5dc26ba010783934d86aa920399237f79dedd5daec9
    - https://solus-project.com/sources/mozilla/firefox-62.0-langpacks.tar.xz : 46e94b5580938e38abc193d297e50b011b081fed93321c7ae95d3e63988c1221
license    :
    - GPL-2.0-or-later
    - MPL-2.0
component  : network.web.browser
summary    : Firefox web browser
description: |
    Mozilla Firefox is an open-source web browser, designed for standards compliance, performance and portability. Its functionality can be enhanced via a plethora of extensions.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(atk)
    - pkgconfig(cairo)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libevent)
    - pkgconfig(libpulse)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(libturbojpeg)
    - pkgconfig(pixman-1)
    - pkgconfig(sqlite3)
    - pkgconfig(vpx)
    - pkgconfig(x11)
    - pkgconfig(xcomposite)
    - pkgconfig(xt)
    - autoconf213
    - bzip2-devel
    - cargo
    - llvm-clang
    - xorg-server-xvfb
    - yasm
rundeps    :
    - ffmpeg
setup      : |
    cp $pkgfiles/mozilla-api-key .
    cp $pkgfiles/config mozconfig
    sed 's@\#\#JOBCOUNT\#\#@%JOBS%@' -i mozconfig

    ./mach configure
build      : |
    # Setup headless X11 to allow firefox to run for the creation of PGO data to optimize with.
    xvfb-run -a -s "-extension GLX" ./mach build

    ./mach buildsymbols
install    : |
    # Install locales first
    langpackdir="$installdir/%libdir%/firefox/browser/extensions"
    install -D -d -m 00755 "${langpackdir}"

    tar xf "${sources}/firefox-${version}-langpacks.tar.xz"
    for i in lang_pack/*.xpi; do
        lname="$(basename ${i})"
        install -D -m 00644 "lang_pack/${lname}" "${langpackdir}"/$lname
    done

    DESTDIR=$installdir ./mach install

    mkdir -p $installdir/usr/share/pixmaps
    ln -sv %libdir%/firefox/browser/chrome/icons/default/default128.png $installdir/usr/share/pixmaps/firefox.png

    ln -sv %libdir%/mozilla/plugins $installdir/%libdir%/firefox/plugins

    install -D -m 00644 $pkgfiles/firefox.desktop $installdir/usr/share/applications/firefox.desktop

    # set up defaults
    mkdir -p $installdir/%libdir%/firefox/browser/defaults/preferences
    install -m 00644 $pkgfiles/prefs.js $installdir/%libdir%/firefox/browser/defaults/preferences/prefs.js
    install -m 00644 $pkgfiles/firefox-l10n.js $installdir/%libdir%/firefox/browser/defaults/preferences/firefox-l10n.js
