name       : firefox
version    : 53.0
release    : 93
source     :
    - https://ftp.mozilla.org/pub/firefox/releases/53.0/source/firefox-53.0.source.tar.xz : 4ed1b23ea7c08f81a08817ddf3b4f06849e01420ee074008b6f390366e95b7d0
    - https://solus-project.com/sources/firefox-53.0-langpacks.tar.xz : cc4a9cff95f1d420c8fa5f97d43b059237e66fbfc8d5c0e9ffd6ceba56f63cff
license    :
    - GPL-2.0+
    - MPL-2.0
summary    : Firefox web browser
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(cairo)
    - pkgconfig(atk)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(alsa)
    - pkgconfig(libpulse)
    - pkgconfig(libevent)
    - pkgconfig(libffi)
    - pkgconfig(hunspell)
    - pkgconfig(nss)
    - pkgconfig(nspr)
    - pkgconfig(pixman-1)
    - pkgconfig(x11)
    - pkgconfig(xt)
    - pkgconfig(sqlite3)
    - pkgconfig(gconf-2.0)
    - pkgconfig(xcomposite)
    - pkgconfig(vpx)
    - libjpeg-turbo-devel
    - yasm
    - autoconf213
    - rust
    - cargo
rundeps     :
    - ffmpeg
component   : network.web.browser
description : |
    Firefox web browser
setup      : |
    # Fix installation directory woes
    %patch -p1 < $pkgfiles/firefox-install-dir.patch

    install $pkgfiles/config mozconfig
    sed 's@\#\#JOBCOUNT\#\#@%JOBS%@' -i mozconfig
build      : |
    # GCC6 produces completely broken Firefox
    export CFLAGS="$CFLAGS -fno-delete-null-pointer-checks -fno-lifetime-dse -fno-schedule-insns2"
    export CXXFLAGS="$CXXFLAGS -fno-delete-null-pointer-checks -fno-lifetime-dse -fno-schedule-insns2"
    %make -f client.mk
install    : |
    # Install locales first
    langpackdir="$installdir/%libdir%/firefox/browser/extensions"
    install -D -d -m 00755 "${langpackdir}"
    
    tar xf "${sources}/firefox-${version}-langpacks.tar.xz"
    for i in lang_pack/*.xpi; do
        lname="$(basename ${i})"
        install -D -m 00644 "lang_pack/${lname}" "${langpackdir}"/$lname
    done
    
    export CFLAGS="$CFLAGS -fno-delete-null-pointer-checks -fno-lifetime-dse -fno-schedule-insns2"
    export CXXFLAGS="$CXXFLAGS -fno-delete-null-pointer-checks -fno-lifetime-dse -fno-schedule-insns2"
    %make_install -f client.mk install INSTALL_SDK= 
    
    mkdir -p $installdir/usr/share/pixmaps
    ln -sv %libdir%/firefox/browser/icons/mozicon128.png $installdir/usr/share/pixmaps/firefox.png
    
    ln -sv %libdir%/mozilla/plugins $installdir/%libdir%/firefox/plugins
      
    install -D -m 00644 $pkgfiles/firefox.desktop $installdir/usr/share/applications/firefox.desktop
    
    # set up defaults
    mkdir -p $installdir/%libdir%/firefox/browser/defaults/preferences
    install -m 00644 $pkgfiles/prefs.js $installdir/%libdir%/firefox/browser/defaults/preferences/prefs.js
    install -m 00644 $pkgfiles/firefox-l10n.js $installdir/%libdir%/firefox/browser/defaults/preferences/firefox-l10n.js
