name        : firefox
version     : 39.0.3
release     : 23
source     :
    - http://ftp.mozilla.org/pub/mozilla.org/firefox/releases/39.0.3/source/firefox-39.0.3.source.tar.bz2 : 8c16df4ce94b30f1308655f9ed6ac3e76aaa2eb3643739b9263226c086d0177b
license     :
    - GPL-2.0+
    - MPL-2.0
summary     : Firefox web browser
builddeps   :
    - pkgconfig(libevent)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(cairo)
    - pkgconfig(atk)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(alsa)
    - pkgconfig(libpulse)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(x11)
    - pkgconfig(xt)
    - pkgconfig(icu-i18n)
    - pkgconfig(sqlite3)
    - pkgconfig(xcomposite)
    - libjpeg-turbo-devel
    - yasm
description : |
    Firefox web browser
setup      : |
    # GTK3 fixes
    %patch -p1 < $pkgfiles/gtk3/mozilla-1073117-no-gap-tab.patch
    %patch -p1 < $pkgfiles/gtk3/mozilla-1161056.patch
    %patch -p1 < $pkgfiles/gtk3/mozilla-1144745-1.patch
    %patch -p1 < $pkgfiles/gtk3/mozilla-1144745-2.patch
    %patch -p1 < $pkgfiles/gtk3/mozilla-1144745-3.patch
    %patch -p1 < $pkgfiles/gtk3/mozilla-1160154.patch
    %patch -p1 < $pkgfiles/gtk3/mozilla-1169233.patch
    %patch -p1 < $pkgfiles/gtk3/mozilla-1169232.patch
    %patch -p1 < $pkgfiles/gtk3/mozilla-1129873-apppicker.patch
    
    install $pkgfiles/config mozconfig
    sed 's@\#\#JOBCOUNT\#\#@%JOBS%@' -i mozconfig
    
    echo "ac_add_options --libdir=%libdir%" >> mozconfig
build      : |
    unset LD_AS_NEEDED
    %make -f client.mk
install    : |
    unset LD_AS_NEEDED
    %make_install -f client.mk install INSTALL_SDK= 
    
    mkdir -p $installdir/usr/share/pixmaps
    ln -sv %libdir%/firefox-${version}/browser/icons/mozicon128.png $installdir/usr/share/pixmaps/firefox.png
    
    mkdir -p $installdir/%libdir%/plugins
    ln -sv %libdir%/mozilla/plugins $installdir/%libdir%/firefox-${version}/plugins
    
    
    install -D -m 00644 $pkgfiles/firefox.desktop $installdir/usr/share/applications/firefox.desktop
