name        : firefox
version     : 48.0
release     : 63
source     :
    - https://ftp.mozilla.org/pub/firefox/releases/48.0/source/firefox-48.0.source.tar.xz : f474113a1ee75a01d43e270bf438ba78b9f7f2e397a66652b43603235fa76e21
    - https://solus-project.com/sources/firefox-48.0-langpacks.tar.xz : aefdc3e28747372452a136fc310c747a8f3b843f79cb4bfa83342ec6d87208b0
license     :
    - GPL-2.0+
    - MPL-2.0
summary     : Firefox web browser
builddeps   :
    - pkgconfig(libevent)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(cairo)
    - pkgconfig(atk)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(alsa)
    - pkgconfig(libpulse)
    - pkgconfig(hunspell)
    - pkgconfig(x11)
    - pkgconfig(xt)
    - pkgconfig(icu-i18n)
    - pkgconfig(sqlite3)
    - pkgconfig(gconf-2.0)
    - pkgconfig(xcomposite)
    - libjpeg-turbo-devel
    - yasm
    - autoconf213
rundeps     :
    - ffmpeg
component   : network.web.browser
description : |
    Firefox web browser
setup      : |
    # Fix installation directory woes
    %patch -p1 < $pkgfiles/firefox-install-dir.patch
    
    # GTK 3.20 integration
    %patch -p1 < $pkgfiles/firefox-gtk3-20.patch
    
    install $pkgfiles/config mozconfig
    sed 's@\#\#JOBCOUNT\#\#@%JOBS%@' -i mozconfig
build      : |
    # GCC6 produces completely broken Firefox
    export CFLAGS="$CFLAGS -fno-delete-null-pointer-checks -fno-lifetime-dse -fno-schedule-insns2"
    export CXXFLAGS="$CXXFLAGS -fno-delete-null-pointer-checks -fno-lifetime-dse -fno-schedule-insns2"
    %make -f client.mk
install    : |
    # Install locales first
    langpackdir="$installdir/%libdir%/firefox/browser/extensions"
    install -D -d -m 00755 "${langpackdir}"
    
    tar xf "${sources}/firefox-${version}-langpacks.tar.xz"
    for i in lang_pack/*.xpi; do
        lname="$(basename ${i})"
        install -D -m 00644 "lang_pack/${lname}" "${langpackdir}"/$lname
    done
    
    export CFLAGS="$CFLAGS -fno-delete-null-pointer-checks -fno-lifetime-dse -fno-schedule-insns2"
    export CXXFLAGS="$CXXFLAGS -fno-delete-null-pointer-checks -fno-lifetime-dse -fno-schedule-insns2"
    %make_install -f client.mk install INSTALL_SDK= 
    
    mkdir -p $installdir/usr/share/pixmaps
    ln -sv %libdir%/firefox/browser/icons/mozicon128.png $installdir/usr/share/pixmaps/firefox.png
    
    ln -sv %libdir%/mozilla/plugins $installdir/%libdir%/firefox/plugins
      
    install -D -m 00644 $pkgfiles/firefox.desktop $installdir/usr/share/applications/firefox.desktop
    
    # set up defaults
    mkdir -p $installdir/%libdir%/firefox/browser/defaults/preferences
    install -m 00644 $pkgfiles/prefs.js $installdir/%libdir%/firefox/browser/defaults/preferences/prefs.js
    install -m 00644 $pkgfiles/firefox-l10n.js $installdir/%libdir%/firefox/browser/defaults/preferences/firefox-l10n.js
