name        : firefox
version     : 47.0.1
release     : 61
source     :
    - https://ftp.mozilla.org/pub/firefox/releases/47.0.1/source/firefox-47.0.1.source.tar.xz : 5ac36c3481dde80ef2e36237badef6cb8ec5fe7e3b5ac1728839477de0cc034c
    - https://solus-project.com/sources/firefox-47.0.1-langpacks.tar.xz : 88773ef50103c2c55431161c4226480c5d5075745e2351eac285901fd2af7d0a
license     :
    - GPL-2.0+
    - MPL-2.0
summary     : Firefox web browser
clang       : no
builddeps   :
    - pkgconfig(libevent)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(cairo)
    - pkgconfig(atk)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(alsa)
    - pkgconfig(libpulse)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(x11)
    - pkgconfig(xt)
    - pkgconfig(icu-i18n)
    - pkgconfig(sqlite3)
    - pkgconfig(gconf-2.0)
    - pkgconfig(xcomposite)
    - libjpeg-turbo-devel
    - yasm
    - autoconf213
component   : network.web.browser
description : |
    Firefox web browser
setup      : |
    # Fix installation directory woes
    %patch -p1 < $pkgfiles/firefox-install-dir.patch
    # From Fedora, allow us to ship system wide extensions
    %patch -p1 < $pkgfiles/Allow-unsigned-addons-in-usr-lib-share-mozilla-exten.patch
        
    install $pkgfiles/config mozconfig
    sed 's@\#\#JOBCOUNT\#\#@%JOBS%@' -i mozconfig
    # Force the libdir
    echo "ac_add_options --libdir=%libdir%" >> mozconfig
build      : |
    # ld-as-needed can go boom here
    unset LD_AS_NEEDED
    
    # Force our flags into the mozconfig properly and enable -O3/flto
    CFLAGS="${CFLAGS/-O2/}"
    CXXFLAGS="${CXXFLAGS/-O2/}"
    export CFLAGS="${CFLAGS} -O3 -ffunction-sections -fno-semantic-interposition -falign-functions=32"
    export CXXFLAGS="${CXXFLAGS} -O3 -ffunction-sections -fno-semantic-interposition -falign-functions=32"
    echo "export CFLAGS=\"${CFLAGS}\"" >> mozconfig
    echo "export CXXFLAGS=\"${CXXFLAGS}\"" >> mozconfig
    echo "export LDFLAGS=\"${LDFLAGS}\"" >> mozconfig
    # Ensure lto works
    echo "export RANLIB=\"gcc-ranlib\"" >> mozconfig
    echo "export AR=\"gcc-ar\"" >> mozconfig
    echo "export NM=\"gcc-nm\"" >> mozconfig
    %make -f client.mk
install    : |
    # Install locales first
    langpackdir="$installdir/%libdir%/firefox/browser/extensions"
    install -D -d -m 00755 "${langpackdir}"
    
    tar xf "${sources}/firefox-${version}-langpacks.tar.xz"
    for i in lang_pack/*.xpi; do
        lname="$(basename ${i})"
        install -D -m 00644 "lang_pack/${lname}" "${langpackdir}"/$lname
    done
    
    %make_install -f client.mk install INSTALL_SDK= 
    
    mkdir -p $installdir/usr/share/pixmaps
    ln -sv %libdir%/firefox/browser/icons/mozicon128.png $installdir/usr/share/pixmaps/firefox.png
    
    ln -sv %libdir%/mozilla/plugins $installdir/%libdir%/firefox/plugins
      
    install -D -m 00644 $pkgfiles/firefox.desktop $installdir/usr/share/applications/firefox.desktop
    
    # set up defaults
    mkdir -p $installdir/%libdir%/firefox/browser/defaults/preferences
    install -m 00644 $pkgfiles/prefs.js $installdir/%libdir%/firefox/browser/defaults/preferences/prefs.js
    install -m 00644 $pkgfiles/firefox-l10n.js $installdir/%libdir%/firefox/browser/defaults/preferences/firefox-l10n.js
