name       : firefox
version    : 73.0
release    : 184
source     :
    - https://ftp.mozilla.org/pub/firefox/releases/73.0/source/firefox-73.0.source.tar.xz : b57af802aae32d7f4624ce8b373701236b76904abcb893ded9e0cb5805ba6e17
    - https://getsol.us/sources/mozilla/firefox-73.0-langpacks.tar.xz : 85e210df0230597c980edac54850c1ed77ec711a7d5d45ba785d03fae05ac7b5
license    :
    - GPL-2.0-or-later
    - MPL-2.0
component  : network.web.browser
summary    : Firefox web browser
description: |
    Mozilla Firefox is an open-source web browser, designed for standards compliance, performance and portability. Its functionality can be enhanced via a plethora of extensions.
clang      : yes
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(atk)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libevent)
    - pkgconfig(libpulse)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(libturbojpeg)
    - pkgconfig(pango)
    - pkgconfig(pixman-1)
    - pkgconfig(sqlite3)
    - pkgconfig(x11)
    - pkgconfig(xcomposite)
    - pkgconfig(xt)
    - autoconf213
    - bzip2-devel
    - cargo
    - cbindgen
    - llvm-clang
    - nodejs-devel
    - noto-sans-ttf
    - xorg-server-xvfb
    - yasm
rundeps    :
    - ffmpeg
environment: |
    export MOZ_NOSPAM=1
    export MOZBUILD_STATE_PATH=$PWD
setup      : |
    cp $pkgfiles/mozilla-api-key .
    cp $pkgfiles/config .mozconfig
    sed 's@\#\#JOBCOUNT\#\#@%JOBS%@' -i .mozconfig
    echo "ac_add_options --with-mozilla-api-keyfile=${workdir}/mozilla-api-key" >> .mozconfig
    pushd third_party/python/psutil/
    patch -p1 < $pkgfiles/Future-proof-disk_io_counters.patch
    popd

    ./mach configure
build      : |
    xvfb-run -a -n 55 -s "-screen 0 1024x768x24 -ac +extension GLX +render -noreset" ./mach build
    ./mach buildsymbols
install    : |
    # Install locales first
    langpackdir="$installdir/%libdir%/firefox/browser/extensions"
    install -D -d -m 00755 "${langpackdir}"

    tar xf "${sources}/firefox-${version}-langpacks.tar.xz"
    for i in ff_lang_pack/*.xpi; do
        lname="$(basename ${i})"
        install -D -m 00644 "ff_lang_pack/${lname}" "${langpackdir}"/$lname
    done

    DESTDIR=$installdir ./mach install

    mkdir -p $installdir/usr/share/pixmaps
    ln -sv %libdir%/firefox/browser/chrome/icons/default/default128.png $installdir/usr/share/pixmaps/firefox.png

    ln -sv %libdir%/mozilla/plugins $installdir/%libdir%/firefox/plugins

    install -D -m 00644 $pkgfiles/firefox.desktop $installdir/usr/share/applications/firefox.desktop

    # set up defaults
    mkdir -p $installdir/%libdir%/firefox/browser/defaults/preferences
    install -m 00644 $pkgfiles/prefs.js $installdir/%libdir%/firefox/browser/defaults/preferences/prefs.js
    install -m 00644 $pkgfiles/firefox-l10n.js $installdir/%libdir%/firefox/browser/defaults/preferences/firefox-l10n.js
