name        : firefox
version     : 42.0
release     : 38
source     :
    - https://ftp.mozilla.org/pub/mozilla.org/firefox/releases/42.0/source/firefox-42.0.source.tar.xz : 994a346699298277b64ec0cab72660b8d3e5b879a2ac79207576f7e6c33da3ae
license     :
    - GPL-2.0+
    - MPL-2.0
summary     : Firefox web browser
clang       : yes
builddeps   :
    - pkgconfig(libevent)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(cairo)
    - pkgconfig(atk)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(alsa)
    - pkgconfig(libpulse)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(x11)
    - pkgconfig(xt)
    - pkgconfig(icu-i18n)
    - pkgconfig(sqlite3)
    - pkgconfig(gconf-2.0)
    - pkgconfig(xcomposite)
    - libjpeg-turbo-devel
    - yasm
description : |
    Firefox web browser
setup      : |
    # GTK3 fixes
    %patch -p1 < $pkgfiles/gtk3/mozilla-1192243.patch
    
    # Fix installation directory woes
    %patch -p1 < $pkgfiles/firefox-install-dir.patch
    
    install $pkgfiles/config mozconfig
    sed 's@\#\#JOBCOUNT\#\#@%JOBS%@' -i mozconfig
    
    echo "ac_add_options --libdir=%libdir%" >> mozconfig
build      : |
    unset LD_AS_NEEDED
    %make -f client.mk
install    : |
    unset LD_AS_NEEDED
    %make_install -f client.mk install INSTALL_SDK= 
    
    mkdir -p $installdir/usr/share/pixmaps
    ln -sv %libdir%/firefox/browser/icons/mozicon128.png $installdir/usr/share/pixmaps/firefox.png
    
    mkdir -p $installdir/%libdir%/plugins
    ln -sv %libdir%/mozilla/plugins $installdir/%libdir%/firefox/plugins
      
    install -D -m 00644 $pkgfiles/firefox.desktop $installdir/usr/share/applications/firefox.desktop
    
    # set up defaults
    mkdir -p $installdir/%libdir%/firefox/browser/defaults/preferences
    install -m 00644 $pkgfiles/prefs.js $installdir/%libdir%/firefox/browser/defaults/preferences/prefs.js
