name       : firefox
version    : 63.0
release    : 142
source     :
    - https://ftp.mozilla.org/pub/firefox/releases/63.0/source/firefox-63.0.source.tar.xz : 3f95b028571ab9ffb3bf637761534a685aed224de3b87eb8ad7e1d0831995c07
    - https://getsol.us/sources/mozilla/firefox-63.0-langpacks.tar.xz : 126854569559d484150f71548b21e6fad5ec281cd94ddf5417d290beacd2c0e6
license    :
    - GPL-2.0-or-later
    - MPL-2.0
component  : network.web.browser
summary    : Firefox web browser
description: |
    Mozilla Firefox is an open-source web browser, designed for standards compliance, performance and portability. Its functionality can be enhanced via a plethora of extensions.
clang      : yes
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(atk)
    - pkgconfig(cairo)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libevent)
    - pkgconfig(libpulse)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(libturbojpeg)
    - pkgconfig(pixman-1)
    - pkgconfig(sqlite3)
    - pkgconfig(vpx)
    - pkgconfig(x11)
    - pkgconfig(xcomposite)
    - pkgconfig(xt)
    - autoconf213
    - bzip2-devel
    - cargo
    - cbindgen
    - llvm-clang
    - nodejs-devel
    - yasm
rundeps    :
    - ffmpeg
setup      : |
    cp $pkgfiles/mozilla-api-key .
    cp $pkgfiles/config mozconfig
    sed 's@\#\#JOBCOUNT\#\#@%JOBS%@' -i mozconfig

    ./mach configure
build      : |
    ./mach build
    ./mach buildsymbols
install    : |
    # Install locales first
    langpackdir="$installdir/%libdir%/firefox/browser/extensions"
    install -D -d -m 00755 "${langpackdir}"

    tar xf "${sources}/firefox-${version}-langpacks.tar.xz"
    for i in lang_pack/*.xpi; do
        lname="$(basename ${i})"
        install -D -m 00644 "lang_pack/${lname}" "${langpackdir}"/$lname
    done

    DESTDIR=$installdir ./mach install

    mkdir -p $installdir/usr/share/pixmaps
    ln -sv %libdir%/firefox/browser/chrome/icons/default/default128.png $installdir/usr/share/pixmaps/firefox.png

    ln -sv %libdir%/mozilla/plugins $installdir/%libdir%/firefox/plugins

    install -D -m 00644 $pkgfiles/firefox.desktop $installdir/usr/share/applications/firefox.desktop

    # set up defaults
    mkdir -p $installdir/%libdir%/firefox/browser/defaults/preferences
    install -m 00644 $pkgfiles/prefs.js $installdir/%libdir%/firefox/browser/defaults/preferences/prefs.js
    install -m 00644 $pkgfiles/firefox-l10n.js $installdir/%libdir%/firefox/browser/defaults/preferences/firefox-l10n.js
